access_link = "https://www.xbox.com/pt-BR/"

[home]
explore_games = "//*[contains(text(), 'Explorar jogos')]/@href"

[games]
all_games = "//*[contains(@href, 'all-games') and not(contains(@href, 'cat'))]/@href"

[all_games]
access_link = "<access_link>/games/all-games"
data_script = "//script[contains(text(), '__PRELOADED_STATE__')]/text()"
products_regex = '(\"products\"\:)(\{\"data\"\:.*?)(,\"indexes\")'

[game]
title = "//*[contains(@class, 'productTitle')]/text()"
# TODO: upd prices xpath?
prices = "//*[contains(@data-m, '{id}')]/*/*[contains(@class, 'Price-module')]/text()"

# End Of File